### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by jgarciao** [flathub/org.flightgear.FlightGear#2]
https://beta.flathub.org/apps/details/org.flightgear.FlightGear does not show the icon of the application because is not present in the repo's appdata data file

**Comment by TingPing** [comment]
The problem is its missing a desktop file...

**Comment by Alexander-Wilms** [comment]
It does install a desktop file, which contains this line: `Icon=org.flightgear.FlightGear`

**Comment by Alexander-Wilms** [comment]
The latest build fixed this: https://beta.flathub.org/apps/details/org.flightgear.FlightGear

The previous build had failed, since a download timed out, not sure if that was the reason.

**Comment by jgarciao** [comment]
Thanks!
