### ISSUE TITLE
main thread segfaults at 3d init

### ISSUE THREAD

**Issue by violetmage** [flathub/org.flightgear.FlightGear#24]
am guessing is from missing "--device=shm"

**Comment by violetmage** [comment]
am using debian 10

**Comment by violetmage** [comment]
trying local build

**Comment by violetmage** [comment]
ah

is no problem

"download scenery automatically" crashes if enabled for first run

disable > first run > enable > run = normal flightgear

_am _sorry__

**Comment by Vanadiae** [comment]
I hadn't had any problem when updating, even though I had this option enabled too.
