### ISSUE TITLE
libGL error

### ISSUE THREAD

**Issue by Murmele** [flathub/org.flightgear.FlightGear#3]
Hello,
when I'm installing Flatpak from Flathub with Gnome Software I get the following errors:
```
flatpak run org.flightgear.FlightGear 
FlightGear:  Version 2017.3.1
FlightGear:  Build Type Release
Built with GNU C++ version 6.2
Jenkins number/ID 0:none
aircraft path not found:Path "/home/martin/.var/app/org.flightgear.FlightGear/data/fgfs/Aircraft"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
getDefaultWindow: failed to create GraphicsContext
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
getDefaultWindow: failed to create GraphicsContext
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```
I use the proprietary nvidia driver under xorg.

Best regards

**Comment by TingPing** [comment]
What is the output of `flatpak --gl-drivers`

**Comment by Murmele** [comment]
The output of flatpak --gl-drivers is: 
nvidia-390-48
default
host

**Comment by TingPing** [comment]
That version is certainly packaged. What does `flatpak list` show

**Comment by Murmele** [comment]
This is the output of flatpak list:
`Ref                                                    Options               
org.flatpak.Hello/x86_64/master                        user,current          
org.flightgear.FlightGear/x86_64/stable                user,current          
org.freedesktop.Sdk.Docs/x86_64/1.6                    user,runtime          
org.gnome.Sdk.Docs/x86_64/3.26                         user,runtime          
org.gnome.Sdk/x86_64/master                            user,runtime          
org.kde.Platform/x86_64/5.10                           user,runtime          
net.ankiweb.Anki/x86_64/stable                         system,current        
net.minetest.Minetest/x86_64/stable                    system,current        
org.filezillaproject.Filezilla/x86_64/stable           system,current        
org.gimp.GIMP/x86_64/stable                            system,current        
org.gnome.Builder/x86_64/stable                        system,current        
org.gnome.Epiphany/x86_64/stable                       system,current        
org.gnome.Glade/x86_64/stable                          system,current        
org.gnome.Polari/x86_64/stable                         system,current        
org.gnome.Recipes/x86_64/stable                        system,current        
org.gnome.Todo/x86_64/stable                           system,current        
org.gnome.clocks/x86_64/stable                         system,current        
org.kicad_pcb.KiCad/x86_64/stable                      system,current        
org.monstruosoft.GIMP/x86_64/master                    system,current        
org.mypaint.MyPaint/x86_64/stable                      system,current        
org.freedesktop.Platform.Compat32/x86_64/1.6           system,runtime        
org.freedesktop.Platform.GL.nvidia-387-22/x86_64/1.4   system,runtime        
org.freedesktop.Platform.GL.nvidia-387-34/x86_64/1.4   system,runtime        
org.freedesktop.Platform.GL.nvidia-390-25/x86_64/1.4   system,runtime        
org.freedesktop.Platform.GL.nvidia-390-42/x86_64/1.4   system,runtime        
org.freedesktop.Platform.GL.nvidia-390-48/x86_64/1.4   system,runtime        
org.freedesktop.Platform.GL32.nvidia-387-22/x86_64/1.4 system,runtime        
org.freedesktop.Platform.GL32.nvidia-387-34/x86_64/1.4 system,runtime        
org.freedesktop.Platform.GL32.nvidia-390-25/x86_64/1.4 system,runtime        
org.freedesktop.Platform.GL32.nvidia-390-42/x86_64/1.4 system,runtime        
org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6        system,runtime        
org.freedesktop.Platform.ffmpeg/x86_64/1.6             system,runtime        
org.freedesktop.Platform/x86_64/1.6                    system,runtime        
org.freedesktop.Sdk.Extension.gfortran-62/x86_64/1.6   system,runtime        
org.freedesktop.Sdk.Extension.openjdk9/x86_64/1.6      system,runtime        
org.freedesktop.Sdk/x86_64/1.6                         system,runtime        
org.gnome.Platform/x86_64/3.22                         system,runtime        
org.gnome.Platform/x86_64/3.24                         system,runtime        
org.gnome.Platform/x86_64/3.26                         system,runtime        
org.gnome.Platform/x86_64/3.28                         system,runtime        
org.gnome.Platform/x86_64/master                       system,runtime        
org.gnome.Sdk/x86_64/3.22                              system,runtime        
org.gnome.Sdk/x86_64/3.24                              system,runtime        
org.gnome.Sdk/x86_64/3.26                              system,runtime        
org.gnome.Sdk/x86_64/3.28                              system,runtime        
org.gnome.Sdk/x86_64/master                            system,runtime        
org.gnome.gedit.Locale/x86_64/stable                   system,runtime,partial
org.kde.Platform/x86_64/5.9                            system,runtime        
org.kde.Sdk/x86_64/5.10                                system,runtime        
org.kde.Sdk/x86_64/5.9                                 system,runtime

**Comment by TingPing** [comment]
And the correct version is installed. No clue whats wrong.

**Comment by Alexander-Wilms** [comment]
Does the latest update help?

**Comment by Murmele** [comment]
I will try it today afternoon.

**Comment by Murmele** [comment]
I updated, but I get the same Error again.

**Comment by Alexander-Wilms** [comment]
Do other flatpak'd 3D games have similar issued?

**Comment by Murmele** [comment]
I tried OpenArena and Lugaru HD and they worked fine

**Comment by paju1986** [comment]
I have the same issue on Debian Testing.

**Comment by Alexander-Wilms** [comment]
I now used the configure option DOpenGL_GL_PREFERENCE=GLVND, did that change anything?

**Comment by Murmele** [comment]
I can try it in a week. I will report it to you when I tested.

Martin

Alexander Wilms <notifications@github.com> schrieb am Sa., 23. Feb. 2019,
10:32:

**Comment by Murmele** [comment]
Now it works fine. Thank you!
