### ISSUE TITLE
Send enhanced metainfo file upstream to benefit everyone

### ISSUE THREAD

**Issue by Vanadiae** [flathub/org.flightgear.FlightGear#37]
It would be nice to upstream the metainfo file in this repository, as it fixes a few things from the one upstream and adds a lot of nice screenshots. Basically upstreaming commit 0c54aa22d61514fb26fe0d4684c85db0998f0d2d and 61b8c9869a532bb65f6f4bf1b7772657f97a2e9e but for their metainfo file. We could then drop the metainfo file here and use the upstream one instead.

It would also be a good idea to ask if the metainfo file could be translated in their workflow too, since it seems like it isn't currently translated in their repo.

**Comment by Alexander-Wilms** [comment]
https://sourceforge.net/p/flightgear/flightgear/merge-requests/336/

**Comment by Alexander-Wilms** [comment]
https://sourceforge.net/p/flightgear/flightgear/merge-requests/336/#e91d
