### ISSUE TITLE
Update to v2018.2.2

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.flightgear.FlightGear#9]

**Comment by Alexander-Wilms** [comment]
Thanks, fixed in https://github.com/flathub/org.flightgear.FlightGear/commit/17b3a3ee1f4d1f6f6944607acde8128aad469acb

**Comment by LeandroStanger** [comment]
@Alexander-Wilms https://flathub.org/builds/#/builders/2/builds/4228

**Comment by Alexander-Wilms** [comment]
Build hast been restarted
