### ISSUE TITLE
FlightGear starts without launcher

### ISSUE THREAD

**Issue by andimachovec** [flathub/org.flightgear.FlightGear#91]
I have FlightGear version 2020.3.19 installed from flathub on my Linux Mint 21.2 system. When starting the application from the menu it launches directly into the flight simulator using default settings, without starting the launcher first. I tried starting from the commandline with "flatpak run org.flightgear.FlightGear", this way I get to see the error message "Launcher requested, but FlightGear was compiled without Qt support"

The launcher started correctly before my last update, must have been version 2020.3.18.

**Comment by Alexander-Wilms** [comment]
Should be fixed now

**Comment by andimachovec** [comment]
> Should be fixed now

Thanks a lot for fixing. Will test as soon as I have the time.
